In [1]:
#sv
import numpy as np
X=np.array([[4,8,2],[4,2,7]])
U,S,VT=np.linalg.svd(X)
n_comp=2
X_recon=np.dot(U[:, :n_comp],np.dot(np.diag(S[:n_comp]),VT[:n_comp, :]))
print("Original Matrix:")
print(X)
print("\nReconstructed Matrix (with reduced dimensions):")
print(X_recon)

Original Matrix:
[[4 8 2]
 [4 2 7]]

Reconstructed Matrix (with reduced dimensions):
[[4. 8. 2.]
 [4. 2. 7.]]
